#!/usr/bin/env sh
wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/EN/ShareCfg/skill_data_template.json -O json/skill_data_template.en.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/CN/ShareCfg/skill_data_template.json -O json/skill_data_template.cn.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/JP/ShareCfg/skill_data_template.json -O json/skill_data_template.jp.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/EN/sharecfgdata/ship_data_template.json -O json/ship_data_template.en.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/CN/sharecfgdata/ship_data_template.json -O json/ship_data_template.cn.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/JP/sharecfgdata/ship_data_template.json -O json/ship_data_template.jp.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/EN/sharecfgdata/ship_skin_words.json -O json/ship_skin_words.en.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/CN/sharecfgdata/ship_skin_words.json -O json/ship_skin_words.cn.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/JP/sharecfgdata/ship_skin_words.json -O json/ship_skin_words.jp.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/EN/ShareCfg/ship_skin_words_extra.json -O json/ship_skin_words_extra.en.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/CN/ShareCfg/ship_skin_words_extra.json -O json/ship_skin_words_extra.cn.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/JP/ShareCfg/ship_skin_words_extra.json -O json/ship_skin_words_extra.jp.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/EN/ShareCfg/name_code.json -O json/name_code.en.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/CN/ShareCfg/name_code.json -O json/name_code.cn.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/JP/ShareCfg/name_code.json -O json/name_code.jp.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/EN/ShareCfg/ship_data_blueprint.json -O json/ship_data_blueprint.en.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/CN/ShareCfg/ship_data_blueprint.json -O json/ship_data_blueprint.cn.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/JP/ShareCfg/ship_data_blueprint.json -O json/ship_data_blueprint.jp.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/EN/ShareCfg/ship_strengthen_blueprint.json -O json/ship_strengthen_blueprint.en.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/CN/ShareCfg/ship_strengthen_blueprint.json -O json/ship_strengthen_blueprint.cn.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/JP/ShareCfg/ship_strengthen_blueprint.json -O json/ship_strengthen_blueprint.jp.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/EN/sharecfgdata/ship_data_breakout.json -O json/ship_data_breakout.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/EN/ShareCfg/ship_strengthen_meta.json -O json/ship_strengthen_meta.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/EN/ShareCfg/ship_meta_breakout.json -O json/ship_meta_breakout.json \
     && wget https://raw.githubusercontent.com/AzurLaneTools/AzurLaneData/main/EN/ShareCfg/ship_data_group.json -O json/ship_data_group.json \
    && echo "Generating..." \
    && ./Generate.hs
